CodeMazeBlog/CodeMazeGuides

strings-csharp/ConvertCharArray2String/ConvertCharArray2String.sln
strings-csharp/ConvertCharArray2String/ConvertCharArray2String/ConvertCharArray2String.csproj
strings-csharp/ConvertCharArray2String/ConvertCharArray2String/Program.cs
strings-csharp/ConvertCharArray2String/ConvertCharArray2StringTests/ConvertCharArray2StringTests.csproj
strings-csharp/ConvertCharArray2String/ConvertCharArray2StringTests/ConvertCharArrayTests.cs

CM-215: Convert char[] to string in C#

---

numbers-csharp/GenerateRandomNumbers/GenerateRandomNumbers.sln
numbers-csharp/GenerateRandomNumbers/GenerateRandomNumbers/GenerateRandomNumbers.csproj
numbers-csharp/GenerateRandomNumbers/GenerateRandomNumbers/Program.cs
numbers-csharp/GenerateRandomNumbers/GenerateRandomNumbersTests/GenerateRandomNumbersTests.cs
numbers-csharp/GenerateRandomNumbers/GenerateRandomNumbersTests/GenerateRandomNumbersTests.csproj
numbers-csharp/README.md

https://content.code-maze.com/browse/CM-276

CM-276:  How to Generate Random Numbers From a Range in C#

---

numbers-csharp/MathInCSharp/MathInCSharp.sln
numbers-csharp/MathInCSharp/MathInCSharp/MathInCSharp.csproj
numbers-csharp/MathInCSharp/MathInCSharp/Program.cs

Source code for the Math in C# article

(CM-119) Math in CSharp

---

aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters.sln
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/Controllers/ValuesController.cs
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/MandatoryQueryStringParameters.csproj
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/Program.cs
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/Properties/launchSettings.json
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/QueryParameters.cs
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/appsettings.Development.json
aspnetcore-webapi/MandatoryQueryStringParameters/MandatoryQueryStringParameters/appsettings.json
aspnetcore-webapi/MandatoryQueryStringParameters/Tests/MandatoryClassPropertiesTests.cs
aspnetcore-webapi/MandatoryQueryStringParameters/Tests/MandatoryParameterTests.cs
aspnetcore-webapi/MandatoryQueryStringParameters/Tests/Tests.csproj

CM-348:Required Query String Parameters in ASP.NET Core

---

csharp-advanced-topics/NugetUsingCLI/CodeMaze.Utilities.TemperatureConverter.sln
csharp-advanced-topics/NugetUsingCLI/CodeMaze.Utilities.TemperatureConverter/CodeMaze.Utilities.TemperatureConverter.csproj
csharp-advanced-topics/NugetUsingCLI/CodeMaze.Utilities.TemperatureConverter/Converter.cs
csharp-advanced-topics/NugetUsingCLI/Tests/ConverterTests.cs
csharp-advanced-topics/NugetUsingCLI/Tests/Tests.csproj

changes for CM-264: How to Create and Publish a NuGet Package with dotnet CLI

CM-264:How to Create and Publish a NuGet Package with dotnet CLI

---

csharp-basic-topics/BreakAndContinueStatementsInCsharp/BreakAndContinueStatementsInCsharp.sln
csharp-basic-topics/BreakAndContinueStatementsInCsharp/BreakAndContinueStatementsInCsharp/BreakAndContinueStatementsInCsharp.csproj
csharp-basic-topics/BreakAndContinueStatementsInCsharp/BreakAndContinueStatementsInCsharp/Program.cs
csharp-basic-topics/BreakAndContinueStatementsInCsharp/Tests/Tests.csproj
csharp-basic-topics/BreakAndContinueStatementsInCsharp/Tests/UnitTests.cs

A simple console application showing the application of break and continue statements in a for and while loop respectively.
All Tests Pass

CM39: Break and Continue Statements in C#

---

csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp.Test/TopLevelStatementsInCSharp.Test.csproj
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp.Test/TopLevelStatementsInCSharpTests.cs
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp.sln
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp/Fridge.cs
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp/OldStyleProgram.cs
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp/TopLevelProgram.cs
csharp-basic-topics/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp/TopLevelStatementsInCSharp.csproj

Issue: https://content.code-maze.com/projects/CM/issues/CM-147
Draft: https://drafts.code-maze.com/?p=61937&preview=true

CM-147: Top Level Statements in C#

---

csharp-arrays/CopyArrayElements/BenchmarkRunner/BenchmarkRunner.csproj
csharp-arrays/CopyArrayElements/BenchmarkRunner/ElementCopierBenchmark.cs
csharp-arrays/CopyArrayElements/BenchmarkRunner/Program.cs
csharp-arrays/CopyArrayElements/CopyArrayElements.sln
csharp-arrays/CopyArrayElements/CopyArrayElements/Article.cs
csharp-arrays/CopyArrayElements/CopyArrayElements/CopyArrayElements.csproj
csharp-arrays/CopyArrayElements/CopyArrayElements/ElementCopier.cs
csharp-arrays/CopyArrayElements/CopyArrayElements/Program.cs
csharp-arrays/CopyArrayElements/Tests/Tests.cs
csharp-arrays/CopyArrayElements/Tests/Tests.csproj
csharp-arrays/README.md

CM-379: Copy Array Elements To New Array in C#

CM-379: Copy Array Elements To New Array in C#

---

csharp-arrays/FindTheMaximumValue/BenchmarkRunner/BenchmarkRunner.csproj
csharp-arrays/FindTheMaximumValue/BenchmarkRunner/ElementFinderBenchmark.cs
csharp-arrays/FindTheMaximumValue/BenchmarkRunner/Program.cs
csharp-arrays/FindTheMaximumValue/FindTheMaximumValue.sln
csharp-arrays/FindTheMaximumValue/FindTheMaximumValue/ElementFinder.cs
csharp-arrays/FindTheMaximumValue/FindTheMaximumValue/FindTheMaximumValue.csproj
csharp-arrays/FindTheMaximumValue/FindTheMaximumValue/Program.cs
csharp-arrays/FindTheMaximumValue/Tests/Tests.cs
csharp-arrays/FindTheMaximumValue/Tests/Tests.csproj

Implementation of Find the maximum value of an array in C# using Console Application

CM-400: Find the Maximum Value of an Array in C#

---

collections-csharp/SortedListInCSharp/SortedListInCSharp.sln
collections-csharp/SortedListInCSharp/SortedListInCSharp/GenericLists.cs
collections-csharp/SortedListInCSharp/SortedListInCSharp/NonGenericLists.cs
collections-csharp/SortedListInCSharp/SortedListInCSharp/Program.cs
collections-csharp/SortedListInCSharp/SortedListInCSharp/SortedListInCSharp.csproj
collections-csharp/SortedListInCSharp/Tests/Tests.csproj
collections-csharp/SortedListInCSharp/Tests/UnitTests.cs

Project
A collection of methods demonstrating using various types of SortedList in C#
Tests
Tests ensure that the various sortedLists have the expected features such as content count, sorting, and datatypes.
All Tests pass

CM-87: SortedList in C#

---

strings-csharp/ConvertInt2String/ConvertInt2String/Program.cs

Modified the number of iterations for each benchmark.

CM-208: Convert int to string in C#

---

async-csharp/TaskRunVsTaskFactoryStartNew/TaskRunVsTaskFactoryStartNew.sln
async-csharp/TaskRunVsTaskFactoryStartNew/TaskRunVsTaskFactoryStartNewTests/TaskRunVsTaskFactoryStartNewTests.cs
async-csharp/TaskRunVsTaskFactoryStartNew/TaskRunVsTaskFactoryStartNewTests/TaskRunVsTaskFactoryStartNewTests.csproj

This solution contains the unit test project only. As the examples are related to tasks, it is not suitable to demonstrate in a single execution thread. All of the article code snippets are from this test project.

CM-284: What is the Difference Between Task.Run and Task.Factory.StartNew

---

csharp-algorithms/BubbleSort/BubbleSort.sln
csharp-algorithms/BubbleSort/BubbleSort/Bubble.cs
csharp-algorithms/BubbleSort/BubbleSort/BubbleSort.csproj
csharp-algorithms/BubbleSort/BubbleSort/Program.cs
csharp-algorithms/BubbleSort/BubbleSortTest/BubbleSortTest.csproj
csharp-algorithms/BubbleSort/BubbleSortTest/BubbleSortTests.cs

Implemented the algorithm and tests

CM-26: Bubble Sort In C#

---

dotnet-testing/NUnitProject/NUnitProject.Tests/CalculatorTests.cs
dotnet-testing/NUnitProject/NUnitProject.Tests/NUnitProject.UnitTests.csproj
dotnet-testing/NUnitProject/NUnitProject.sln
dotnet-testing/NUnitProject/NUnitProject/Calculator.cs
dotnet-testing/NUnitProject/NUnitProject/NUnitProject.csproj

CM-34: Unit Testing with NUnit in C#

---

files-csharp/ByteArrayToFile/ByteArrayToFile.sln
files-csharp/ByteArrayToFile/ByteArrayToFile/ByteArrayToFile.csproj
files-csharp/ByteArrayToFile/ByteArrayToFile/ByteArrayToFileConverter.cs
files-csharp/ByteArrayToFile/ByteArrayToFileTest/ByteArrayToFileTest.csproj
files-csharp/ByteArrayToFile/ByteArrayToFileTest/ByteArrayToFileUnitTest.cs
files-csharp/ByteArrayToFile/ByteArrayToFileTest/LiveByteArrayToFileUnitTest.cs

Add code implementation for the 'Convert Byte Array to File' article.

CM-367: Convert Byte Array To File

---

collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIterating.sln
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIterating/RemoveFromListWhileIterating.csproj
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIterating/RemoveFromListWhileIteratingProgram.cs
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIteratingBenchMark/RemoveFromListWhileIteratingBenchmark.cs
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIteratingBenchMark/RemoveFromListWhileIteratingBenchmark.csproj
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIteratingTests/RemoveFromListWhileIteratingTests.cs
collections-csharp/RemoveFromListWhileIterating/RemoveFromListWhileIteratingTests/RemoveFromListWhileIteratingTests.csproj

This is the sample code for CM-241 including tests and performance checks

CM-241: How to Remove Elements From a Generic List in Iteration With C#

---

csharp-basic-topics/TypesOfInheritanceInCSharp/Tests/Tests.csproj
csharp-basic-topics/TypesOfInheritanceInCSharp/Tests/TypesOfInheritanceTest.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp.sln
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/AndroidSmartphone.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/ConvertibleNotebook.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/ILaptop.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/Laptop.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/MobileDevice.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/Program.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/Smartphone.cs
csharp-basic-topics/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp/TypesOfInheritanceInCSharp.csproj

CM-32: Types Of Inheritance In C#

CM-32:Types of inheritance

---

csharp-arrays/SumUpArrayElements/BenchmarkRunner/BenchmarkRunner.csproj
csharp-arrays/SumUpArrayElements/BenchmarkRunner/Program.cs
csharp-arrays/SumUpArrayElements/BenchmarkRunner/SumArrayElementsBenchmark.cs
csharp-arrays/SumUpArrayElements/SumUpArrayElements.sln
csharp-arrays/SumUpArrayElements/SumUpArrayElements/Program.cs
csharp-arrays/SumUpArrayElements/SumUpArrayElements/SumArrayElements.cs
csharp-arrays/SumUpArrayElements/SumUpArrayElements/SumUpArrayElements.csproj
csharp-arrays/SumUpArrayElements/Tests/Tests.cs
csharp-arrays/SumUpArrayElements/Tests/Tests.csproj

Implementation of the Sum Up an Array of Integers in C#

CM-398: Sum Up an Array of Integers in C#

---

csharp-arrays/CompareArrays/BenchmarkRunner/ArrayComparerBenchmark.cs
csharp-arrays/CompareArrays/BenchmarkRunner/BenchmarkRunner.csproj
csharp-arrays/CompareArrays/BenchmarkRunner/Program.cs
csharp-arrays/CompareArrays/CompareArrays.sln
csharp-arrays/CompareArrays/CompareArrays/ArrayComparer.cs
csharp-arrays/CompareArrays/CompareArrays/Article.cs
csharp-arrays/CompareArrays/CompareArrays/CompareArrays.csproj
csharp-arrays/CompareArrays/CompareArrays/Program.cs
csharp-arrays/CompareArrays/Tests/Tests.cs
csharp-arrays/CompareArrays/Tests/Tests.csproj

Implementation of the compare arrays in c#.

CM-391: Implementation of the Compare Arrays in C#

---

strings-csharp/StringBuilderType/BenchmarkRunner/BenchmarkRunner.csproj
strings-csharp/StringBuilderType/BenchmarkRunner/Program.cs
strings-csharp/StringBuilderType/BenchmarkRunner/StringBuilderBenchmark.cs
strings-csharp/StringBuilderType/StringBuilderType.sln
strings-csharp/StringBuilderType/StringBuilderType/Program.cs
strings-csharp/StringBuilderType/StringBuilderType/StringBuilderMethods.cs
strings-csharp/StringBuilderType/StringBuilderType/StringBuilderType.csproj
strings-csharp/StringBuilderType/Tests/Tests.cs
strings-csharp/StringBuilderType/Tests/Tests.csproj

[CM-100](https://content.code-maze.com/browse/CM-100)
StringBuilder in C#

CM-100: StringBuilder in C#

---

authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication.sln
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Controllers/AccountController.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Controllers/LoginRedirectController.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Controllers/WeatherForecastController.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Data/DbInitializer.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/LoginContext.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Models/LoginModel.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Models/Tokens.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Models/WeatherForecast.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/PasswordlessAuthentication.csproj
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Program.cs
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/Properties/launchSettings.json
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/appsettings.Development.json
authorization-dotnet/PasswordlessAuthentication/PasswordlessAuthentication/appsettings.json
authorization-dotnet/PasswordlessAuthentication/Tests/TestUserManager.cs
authorization-dotnet/PasswordlessAuthentication/Tests/Tests.csproj
authorization-dotnet/PasswordlessAuthentication/Tests/UnitTest.cs

Passwordless Authentication in ASP dotnet with dotnet 6, Entity Framework and Identity.
Replaces #414

CM-139: Passwordless Authentication

---

exception-handling/Try-Catch/Tests/Tests/Tests.cs
exception-handling/Try-Catch/Tests/Tests/Tests.csproj
exception-handling/Try-Catch/Try-Catch.sln
exception-handling/Try-Catch/Try-catch/Program.cs
exception-handling/Try-Catch/Try-catch/Try-Catch.csproj
exception-handling/Try-Catch/Try-catch/TryCatchSampleSetup.cs

This PR was created to add try-catch samples code mentioned in the article.

CM-97: Try-catch implementation

---

json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass.sln
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass.csproj
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass/JSON/HondaCivic.json
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass/POCO/Car.cs
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClass/Program.cs
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClassTests/DeserializeJsonToPocoClassTests.cs
json-csharp/DeserializeJsonToPocoClass/DeserializeJsonToPocoClassTests/DeserializeJsonToPocoClassTests.csproj

Opening PR for article CM-467 Deserialize JSON to a C# POCO class

CM-467 - Deserialize JSON to a C# POCO class

---

dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods.Tests/ArticleRepositoryTests.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods.Tests/Mock/FakeDb.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods.Tests/Mock/FakeDbArticleMock.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods.Tests/MockAsynchronousMethods.Tests.csproj
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods.sln
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/ArticleRepository.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/DbModels/ArticleDbModel.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/FakeDatabase/FakeDbArticles.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/Interfaces/IArticleRepository.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/Interfaces/IFakeDbArticles.cs
dotnet-testing/MockAsynchronousMethods/MockAsynchronousMethods/MockAsynchronousMethods.Repository.csproj

Implementation of Mock Asynchronous Methods using Moq

CM-515: Mock Asynchronous Methods Using Moq

---

csharp-algorithms/BucketSort/BucketSort.sln
csharp-algorithms/BucketSort/BucketSort/BucketSort.csproj
csharp-algorithms/BucketSort/BucketSort/BucketSortMethods.cs
csharp-algorithms/BucketSort/BucketSort/Program.cs
csharp-algorithms/BucketSort/BucketSortTests/BucketSortTests.csproj
csharp-algorithms/BucketSort/BucketSortTests/BucketSortUnitTests.cs

The performance benchmarks take way too long to run and even longer on the non-optimized solutions. Please investigate if the same issue happens on your end.

CM-458: Bucket Sort in C#

---

csharp-algorithms/RadixSort/RadixSort.sln
csharp-algorithms/RadixSort/RadixSort/Program.cs
csharp-algorithms/RadixSort/RadixSort/RadixSort.csproj
csharp-algorithms/RadixSort/RadixSort/RadixSortMethods.cs
csharp-algorithms/RadixSort/RadixSortTests/RadixSortTests.csproj
csharp-algorithms/RadixSort/RadixSortTests/RadixSortUnitTests.cs
csharp-algorithms/RadixSort/RadixSortTests/Usings.cs

Let me know what you think about the performance tests I have used this time.

CM-460: Radix Sort in C#

---

csharp-advanced-topics/IntroductionToRegexInCSharp/IntroductionToRegexInCSharp.Test/IntroductionToRegexInCSharp.Test.csproj
csharp-advanced-topics/IntroductionToRegexInCSharp/IntroductionToRegexInCSharp.Test/IntroductionToRegexTests.cs
csharp-advanced-topics/IntroductionToRegexInCSharp/IntroductionToRegexInCSharp.sln

Work item: (https://content.code-maze.com/browse/CM-261)
Article draft: (https://drafts.code-maze.com/wp-admin/post.php?post=70754&action=edit)

CM-261: Introduction to Regular Expressions in C#

---

csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp.sln
csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp/Base.cs
csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp/Derived.cs
csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp/MethodOverloadingInCsharp.csproj
csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp/Overload.cs
csharp-intermediate-topics/MethodOverloadingInCsharp/MethodOverloadingInCsharp/Program.cs
csharp-intermediate-topics/MethodOverloadingInCsharp/Tests/MethodOverloadingTest.cs
csharp-intermediate-topics/MethodOverloadingInCsharp/Tests/Tests.csproj

Method Overloading in C#

---

dotnet-projects/windows-service/CodeMazeWorkerService.sln
dotnet-projects/windows-service/CodeMazeWorkerService/CodeMazeWorkerService.csproj
dotnet-projects/windows-service/CodeMazeWorkerService/Program.cs
dotnet-projects/windows-service/CodeMazeWorkerService/Properties/launchSettings.json
dotnet-projects/windows-service/CodeMazeWorkerService/Worker.cs
dotnet-projects/windows-service/CodeMazeWorkerService/appsettings.Development.json
dotnet-projects/windows-service/CodeMazeWorkerService/appsettings.json
dotnet-projects/windows-service/Tests/CodeMazeWorkerServiceTests.cs
dotnet-projects/windows-service/Tests/Tests.csproj

Code changes for CM-56 : Running .NET (Core) Applications as a Service on Windows

CM-56 : Running .NET (Core) Applications as a Service on Windows

---

collections-arrays/ConvertStringArrayToString/BenchmarkRunner/ArrayConverterBenchmark.cs
collections-arrays/ConvertStringArrayToString/BenchmarkRunner/BenchmarkRunner.csproj
collections-arrays/ConvertStringArrayToString/BenchmarkRunner/Program.cs
collections-arrays/ConvertStringArrayToString/StringArrayToString.sln
collections-arrays/ConvertStringArrayToString/StringArrayToString/ArrayConverter.cs
collections-arrays/ConvertStringArrayToString/StringArrayToString/Program.cs
collections-arrays/ConvertStringArrayToString/StringArrayToString/StringArrayToString.csproj
collections-arrays/ConvertStringArrayToString/Tests/Tests.cs
collections-arrays/ConvertStringArrayToString/Tests/Tests.csproj
collections-arrays/ConvertStringArrayToString/Tests/Usings.cs

PR: How to Convert String Array to String in C#

CM-395: How to Convert String Array to String in C#

---

collections-arrays/HowToMergeArrays/HowToMergeArrays.sln
collections-arrays/HowToMergeArrays/HowToMergeArrays/HowToMergeArrays.csproj
collections-arrays/HowToMergeArrays/HowToMergeArrays/MergeArrayBenchmark.cs
collections-arrays/HowToMergeArrays/HowToMergeArrays/Program.cs
collections-arrays/HowToMergeArrays/Tests/Tests.cs
collections-arrays/HowToMergeArrays/Tests/Tests.csproj

Creating a PR for implementation of Merge Arrays comparison and benchmarks in C#.

CM-382: How to Merge Arrays in C#

---

dotnet-projects/linux-service/CodeMazeLinuxWorker.sln
dotnet-projects/linux-service/CodeMazeLinuxWorker/CodeMazeLinuxWorker.csproj
dotnet-projects/linux-service/CodeMazeLinuxWorker/Program.cs
dotnet-projects/linux-service/CodeMazeLinuxWorker/Properties/launchSettings.json
dotnet-projects/linux-service/CodeMazeLinuxWorker/Worker.cs
dotnet-projects/linux-service/CodeMazeLinuxWorker/appsettings.Development.json
dotnet-projects/linux-service/CodeMazeLinuxWorker/appsettings.json
dotnet-projects/linux-service/Tests/CodeMazeLinuxWorkerTest.cs
dotnet-projects/linux-service/Tests/Tests.csproj

Code changes for CM-364- Running .NET (Core) Applications as a Service on Linux

CM-364: Running .NET (Core) Applications as a Service on Linux

---

collections-lists/ConcatenateLists/BenchmarkRunner/BenchmarkRunner.csproj
collections-lists/ConcatenateLists/BenchmarkRunner/ConcatenatorBenchmark.cs
collections-lists/ConcatenateLists/BenchmarkRunner/Program.cs
collections-lists/ConcatenateLists/ConcatenateLists.sln
collections-lists/ConcatenateLists/ConcatenateLists/ConcatenateLists.csproj
collections-lists/ConcatenateLists/ConcatenateLists/Concatenator.cs
collections-lists/ConcatenateLists/ConcatenateLists/Program.cs
collections-lists/ConcatenateLists/Tests/Tests.cs
collections-lists/ConcatenateLists/Tests/Tests.csproj
collections-lists/ConcatenateLists/Tests/Usings.cs

Implementation to concatenate two lists in C#

CM393: Concatenate Lists in C#

---

aspnetcore-webapi/ReturnTypes/APIReturnType.sln
aspnetcore-webapi/ReturnTypes/APIReturnType/APIReturnType.csproj
aspnetcore-webapi/ReturnTypes/APIReturnType/Controllers/EmployeeActionResultController.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/Controllers/EmployeeController.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/Controllers/EmployeeIActionResultController.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/Employee.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/FakeRepository.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/IFakeRepository.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/Program.cs
aspnetcore-webapi/ReturnTypes/APIReturnType/Properties/launchSettings.json
aspnetcore-webapi/ReturnTypes/APIReturnType/appsettings.Development.json
aspnetcore-webapi/ReturnTypes/APIReturnType/appsettings.json
aspnetcore-webapi/ReturnTypes/Tests/Tests/EmployeeActionResultControllerTest.cs
aspnetcore-webapi/ReturnTypes/Tests/Tests/EmployeeControllerTest.cs
aspnetcore-webapi/ReturnTypes/Tests/Tests/EmployeeIActionResultControllerTest.cs
aspnetcore-webapi/ReturnTypes/Tests/Tests/Tests.csproj

Changes for CM-128: ASP.NET Core Web API Action Return Types

CM-128: ASP.NET Core Web API Action Return Types

---

csharp-advanced-topics/GenericsInCSharp/GenericsInCSharp/GenericArray.cs
csharp-advanced-topics/GenericsInCSharp/GenericsInCSharp/GenericDelegates.cs
csharp-advanced-topics/GenericsInCSharp/GenericsInCSharp/Program.cs

Spacing and naming improvements

CM-33: Using Generics in C# 

---

dotnet-testing/FluentAssertions/FluentAssertionsTests.sln
dotnet-testing/FluentAssertions/FluentAssertionsTests/Customer.cs
dotnet-testing/FluentAssertions/FluentAssertionsTests/FluentAssertionsTests.cs
dotnet-testing/FluentAssertions/FluentAssertionsTests/FluentAssertionsTests.csproj
dotnet-testing/FluentAssertions/FluentAssertionsTests/SpecialCustomer.cs

Improving Unit Tests with Fluent Assertions
https://content.code-maze.com/browse/CM-560?filter=-1

CM-560: Improving Unit Tests with Fluent Assertions

---

exception-handling/NullReferenceException/NullReferenceException/ExceptionMethods.cs
exception-handling/NullReferenceException/NullReferenceException/NullReference.csproj
exception-handling/NullReferenceException/NullReferenceException/Program.cs
exception-handling/NullReferenceException/NullReferenceException/Teacher.cs
exception-handling/NullReferenceException/NullReferenceExceptionInCSharp.sln
exception-handling/NullReferenceException/NullReferenceExceptionTests/NullReferenceExceptionUnitTests.cs
exception-handling/NullReferenceException/NullReferenceExceptionTests/NullReferenceTests.csproj
exception-handling/NullReferenceException/NullReferenceExceptionTests/Usings.cs

CM-573: What is NullReferenceException in C#?

---

csharp-intermediate-topics/PathClassCsharp/PathClassCsharp.sln
csharp-intermediate-topics/PathClassCsharp/PathClassCsharp/PathClassCsharp.csproj
csharp-intermediate-topics/PathClassCsharp/PathClassCsharp/PathSamples.cs
csharp-intermediate-topics/PathClassCsharp/PathClassCsharp/Program.cs
csharp-intermediate-topics/PathClassCsharp/PathClassCsharp/Properties/launchSettings.json
csharp-intermediate-topics/PathClassCsharp/Tests/PathClassCsharpUnitTest.csproj
csharp-intermediate-topics/PathClassCsharp/Tests/PathClassTest.cs
csharp-intermediate-topics/PathClassCsharp/Tests/Usings.cs

CM-569 Path Class in C#

---

strings-csharp/FirstLetterToUpper/FirstLetterToUpper.sln
strings-csharp/FirstLetterToUpper/FirstLetterToUpper/FirstLetterToUpper.csproj
strings-csharp/FirstLetterToUpper/FirstLetterToUpper/FirstLetterToUpperMethods.cs
strings-csharp/FirstLetterToUpper/FirstLetterToUpper/Program.cs
strings-csharp/FirstLetterToUpper/FirstLetterToUpperTests/FirstLetterToUpperTests.csproj
strings-csharp/FirstLetterToUpper/FirstLetterToUpperTests/FirstLetterToUpperUnitTests.cs
strings-csharp/FirstLetterToUpper/FirstLetterToUpperTests/Usings.cs

CM-234: Make first letter of a string upper case in C#

---

collections-csharp/SortedSetInCSharp/SortedSetInCSharp.sln
collections-csharp/SortedSetInCSharp/SortedSetInCSharp/Program.cs
collections-csharp/SortedSetInCSharp/SortedSetInCSharp/SortedSetInCSharp.csproj
collections-csharp/SortedSetInCSharp/SortedSetInCSharp/SortedSetMethods.cs
collections-csharp/SortedSetInCSharp/SortedSetInCSharpTests/SortedSetInCSharpTests.csproj
collections-csharp/SortedSetInCSharp/SortedSetInCSharpTests/SortedSetInCSharpUnitTests.cs
collections-csharp/SortedSetInCSharp/SortedSetInCSharpTests/Usings.cs

CM-598: SortedSet in C#

---

collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharp.sln
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharp.csproj
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharp/Operations.cs
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharp/Program.cs
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharpTests/HashSetvsSortedSetInCSharpTests.csproj
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharpTests/HashSetvsSortedSetUnitTests.cs
collections-csharp/HashSetvsSortedSetInCSharp/HashSetvsSortedSetInCSharpTests/Usings.cs

CM-599: HashSet vs SortedSet in C#

---

strings-csharp/StringInterpolation/StringInterpolation.sln
strings-csharp/StringInterpolation/StringInterpolationDemo/BasicStrings.cs
strings-csharp/StringInterpolation/StringInterpolationDemo/EscapedStrings.cs
strings-csharp/StringInterpolation/StringInterpolationDemo/Program.cs
strings-csharp/StringInterpolation/StringInterpolationDemo/StringInterpolationDemo.csproj
strings-csharp/StringInterpolation/StringInterpolationDemo/VerbatimAndRawStrings.cs
strings-csharp/StringInterpolation/Tests/BasicStringsUnitTest.cs
strings-csharp/StringInterpolation/Tests/EscapedStringsUnitTest.cs
strings-csharp/StringInterpolation/Tests/Tests.csproj
strings-csharp/StringInterpolation/Tests/Usings.cs
strings-csharp/StringInterpolation/Tests/VerbatimAndRawStringsUnitTest.cs

Hi @MarinkoSpasojevic,
Please have a look at these examples for the string interpolation article.

CM-190: String interpolation

---

dotnet-efcore/ExecuteStoredProceduresInEFCore/ExecuteStoredProcedures/Migrations/202211082221_Init.cs
dotnet-efcore/ExecuteStoredProceduresInEFCore/ExecuteStoredProcedures/UpdateMethods.cs
dotnet-efcore/ExecuteStoredProceduresInEFCore/Tests/ExecuteStoredProceduresInEFCoreLiveTest.cs

- implemented a method UpdateStudentMarkWithReturnValueSqlRaw

CM-622: How to Execute Stored Procedures with EF Core

---

csharp-intermediate-topics/GetListOfProperties/GetListOfProperties.sln
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/Entity/Configuration.cs
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/Entity/Person.cs
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/Entity/User.cs
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/GetListOfProperties.csproj
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/Program.cs
csharp-intermediate-topics/GetListOfProperties/GetListOfProperties/PropertiesRetriever.cs
csharp-intermediate-topics/GetListOfProperties/Tests/Tests.cs
csharp-intermediate-topics/GetListOfProperties/Tests/Tests.csproj
csharp-intermediate-topics/GetListOfProperties/Tests/Usings.cs

The Get List of properties implementation

CM-606: How to Get The List of Properties in C#?

---

collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsInCSharp.sln
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsInCSharp/Program.cs
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsInCSharp/RandomizeGenericListsInCSharp.csproj
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsInCSharp/RandomizeGenericListsMethods.cs
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsTests/RandomizeGenericListsTests.csproj
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsTests/RandomizeGenericListsUnitTests.cs
collections-lists/RandomizeGenericListsInCSharp/RandomizeGenericListsTests/Usings.cs

CM-572: How to Randomize a List<T> in C#

---

json-csharp/HowToGetFormattedJson/HowToGetFormattedJson/Program.cs

Updated to include `JsonConvert.DefaultSettings`

CM-450: How to Get Formatted JSON in .NET using C#?

---

csharp-basic-topics/DifferentTypesOfCommentsInCSharp/.editorconfig
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp.sln
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp.csproj
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/DocumentationComments.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/MixedLineComments.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/MultiLineComments.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/Program.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/DifferentTypesOfCommentsInCSharp/SingleLineComments.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/DocumentationCommentsUnitTest.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/MixedLineCommentsUnitTest.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/MultiLineCommentsUnitTest.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/SingleLineCommentsUnitTest.cs
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/Tests.csproj
csharp-basic-topics/DifferentTypesOfCommentsInCSharp/Tests/Usings.cs

New Article: Different Types of Comments in C#

CM-581: Different Types of Comments in C#

---

csharp-basic-topics/ReturnMultipleValues/ReturnMultipleValues.sln
csharp-basic-topics/ReturnMultipleValues/ReturnMultipleValues/MultipleValues.cs
csharp-basic-topics/ReturnMultipleValues/ReturnMultipleValues/MultipleValuesReturner.cs
csharp-basic-topics/ReturnMultipleValues/ReturnMultipleValues/Program.cs
csharp-basic-topics/ReturnMultipleValues/ReturnMultipleValues/ReturnMultipleValues.csproj
csharp-basic-topics/ReturnMultipleValues/Tests/Tests.cs
csharp-basic-topics/ReturnMultipleValues/Tests/Tests.csproj
csharp-basic-topics/ReturnMultipleValues/Tests/Usings.cs

Implementation of the Return Multiple Values to a Method Caller in C#

CM-238: Return multiple values to a method caller in C#

---

collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.Benchmark/DeleteElementsFromArray.Benchmark.csproj
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.Benchmark/DeleteElementsFromArrayBenchmark.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.Benchmark/Program.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.sln
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/DeleteElementsFromArray.csproj
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithArrayCopy.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithArraySegment.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithFindAllMethod.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithLoopMethod.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithRemoveAllMethod.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithWhereMethod.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Program.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArrayUnitTests/DeleteElementsFromArrayUnitTests.cs
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArrayUnitTests/Tests.csproj
collections-arrays/DeleteElementsFromArray/DeleteElementsFromArrayUnitTests/Usings.cs

I committed the branch regarding the CM-397 issue. Please for your review.

CM-397: How to Delete Elements from an Array in C#?

---

dotnet-logging/LoggingFromStartup/LoggingFromProgram/LoggingFromProgram.csproj
dotnet-logging/LoggingFromStartup/LoggingFromProgram/Program.cs
dotnet-logging/LoggingFromStartup/LoggingFromProgram/Properties/launchSettings.json
dotnet-logging/LoggingFromStartup/LoggingFromProgram/appsettings.Development.json
dotnet-logging/LoggingFromStartup/LoggingFromProgram/appsettings.json
dotnet-logging/LoggingFromStartup/LoggingFromStartup.sln
dotnet-logging/LoggingFromStartup/LoggingFromStartup/Controllers/WeatherForecastController.cs
dotnet-logging/LoggingFromStartup/LoggingFromStartup/LoggingFromStartup.csproj
dotnet-logging/LoggingFromStartup/LoggingFromStartup/Program.cs
dotnet-logging/LoggingFromStartup/LoggingFromStartup/Properties/launchSettings.json
dotnet-logging/LoggingFromStartup/LoggingFromStartup/Startup.cs
dotnet-logging/LoggingFromStartup/LoggingFromStartup/WeatherForecast.cs
dotnet-logging/LoggingFromStartup/LoggingFromStartup/appsettings.Development.json
dotnet-logging/LoggingFromStartup/LoggingFromStartup/appsettings.json
dotnet-logging/LoggingFromStartup/Tests/LoggingFromProgramTest.cs
dotnet-logging/LoggingFromStartup/Tests/LoggingFromStartupTest.cs
dotnet-logging/LoggingFromStartup/Tests/Tests.csproj
dotnet-logging/LoggingFromStartup/Tests/Usings.cs

CM-167 : How do I write logs from within Startup.cs/Program.cs?

CM-167 : How to write logs from within Startup.cs/Program.cs

---

csharp-basic-topics/ValidateEmailAddress/Tests/EmailValidatorTests.cs
csharp-basic-topics/ValidateEmailAddress/Tests/Tests.csproj
csharp-basic-topics/ValidateEmailAddress/Tests/Usings.cs
csharp-basic-topics/ValidateEmailAddress/ValidateEmailAddress.sln
csharp-basic-topics/ValidateEmailAddress/ValidateEmailAddress/EmailValidator.cs
csharp-basic-topics/ValidateEmailAddress/ValidateEmailAddress/Fluent/EmailFluntValidator.cs
csharp-basic-topics/ValidateEmailAddress/ValidateEmailAddress/Program.cs
csharp-basic-topics/ValidateEmailAddress/ValidateEmailAddress/ValidateEmailAddress.csproj

CM-236: How to validate email address in C#

---

dotnet-efcore/EFCoreInserts/EFCoreInserts.sln
dotnet-efcore/EFCoreInserts/EFInserts-EF6-Tests/EFInserts-EF6-Tests.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EF6-Tests/TestModelTests.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6-Tests/Usings.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6/EFInserts-EF6.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EF6/Model.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6/ModelConfiguration.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6/ModelContext.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6/Program.cs
dotnet-efcore/EFCoreInserts/EFInserts-EF6/TestModel.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6-Tests/EFInserts-EFCore6-Tests.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6-Tests/TestModelTests.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6-Tests/Usings.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6/EFInserts-EFCore6.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6/Model.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6/ModelContext.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6/Program.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore6/TestModel.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7-Tests/EFInserts-EFCore7-Tests.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7-Tests/TestModelTests.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7-Tests/Usings.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7/EFInserts-EFCore7.csproj
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7/Model.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7/ModelContext.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7/Program.cs
dotnet-efcore/EFCoreInserts/EFInserts-EFCore7/TestModel.cs

CM-406: Fast Inserts With Entity Framework

---

csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharp.sln
csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharp/Program.cs
csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharp/SizeOfOperatorInCSharp.csproj
csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharpTests/SizeOfOperatorInCSharpTests.csproj
csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharpTests/SizeOfOperatorUnitTests.cs
csharp-basic-topics/SizeOfOperatorInCSharp/SizeOfOperatorInCSharpTests/Usings.cs

CM-433: Using sizeof() Operator in C#

---

strings-csharp/StringReverse/StrinReverseUnitTest/StringReverseUnitTest.cs
strings-csharp/StringReverse/StrinReverseUnitTest/StringReverseUnitTest.csproj
strings-csharp/StringReverse/StrinReverseUnitTest/Usings.cs
strings-csharp/StringReverse/StringReverse.Benchmark/Program.cs
strings-csharp/StringReverse/StringReverse.Benchmark/StringReverse.Benchmark.csproj
strings-csharp/StringReverse/StringReverse.Benchmark/StringReverseBenchmark.cs
strings-csharp/StringReverse/StringReverse.sln
strings-csharp/StringReverse/StringReverse/Methods/ArrayReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/EnumerableReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/RecursiveStringReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/ReverseXorMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/StackReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/StringBuilderReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/StringCreateMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/StringExtensionReverseMethod.cs
strings-csharp/StringReverse/StringReverse/Methods/TextElementEnumeratorMethod.cs
strings-csharp/StringReverse/StringReverse/Program.cs
strings-csharp/StringReverse/StringReverse/StringReverse.csproj

Here is the first commit for Reversing a String in c#. Please for your review.

CM-402: How to Reverse a String in C#

---

dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net.sln
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/Controllers/LogTestController.cs
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/Log4netExtensions.cs
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/Program.cs
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/Properties/launchSettings.json
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net.csproj
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/appsettings.Development.json
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/appsettings.json
dotnet-logging/StructuredLoggingUsingLog4Net/StructuredLoggingUsingLog4Net/log4net.config
dotnet-logging/StructuredLoggingUsingLog4Net/Tests/LogTestControllerTests.cs
dotnet-logging/StructuredLoggingUsingLog4Net/Tests/StructuredLoggingUsingLog4netTests.cs
dotnet-logging/StructuredLoggingUsingLog4Net/Tests/Tests.csproj
dotnet-logging/StructuredLoggingUsingLog4Net/Tests/Usings.cs

CM-669 : Structured Logging in ASP.NET Core With log4net

---

json-csharp/CamelCaseSerialization/CamelCaseSerialization.sln
json-csharp/CamelCaseSerialization/CamelCaseSerialization/CamelCaseSerialization.csproj
json-csharp/CamelCaseSerialization/CamelCaseSerialization/JsonSerializerExtensions.cs
json-csharp/CamelCaseSerialization/CamelCaseSerialization/Person.cs
json-csharp/CamelCaseSerialization/CamelCaseSerialization/PersonWithAttributes.cs
json-csharp/CamelCaseSerialization/CamelCaseSerialization/Program.cs
json-csharp/CamelCaseSerialization/Tests/CamelCaseSerialization.Tests/CamelCaseSerialization.Tests.csproj
json-csharp/CamelCaseSerialization/Tests/CamelCaseSerialization.Tests/ExtensionTests.cs
json-csharp/CamelCaseSerialization/Tests/CamelCaseSerialization.Tests/Usings.cs

This is a console application code demo for [CM-322 Using System.Text.Json for Camel Case Serialization](https://content.code-maze.com/browse/CM-322)https://[content.code-maze.com/browse/CM-322](https://content.code-maze.com/browse/CM-322)

CM-322 Using System.Text.Json for Camel Case Serialization

---

aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate.sln
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/Controllers/WeatherForecastController.cs
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate.csproj
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/Program.cs
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/Properties/launchSettings.json
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/WeatherForecast.cs
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/appsettings.Development.json
aspnetcore-features/HowToSetupDeveloperHttpsCertificate/HowToSetupDeveloperHttpsCertificate/appsettings.json

Created brand new asp net core web api project with https enabled with no other changes made

CM-645: How To Set Up SSL Certificate In Visual Studio

---

csharp-basic-topics/GetClassNameInCSharp/GetClassNameInCSharp.sln
csharp-basic-topics/GetClassNameInCSharp/GetClassNameInCSharp/Car.cs
csharp-basic-topics/GetClassNameInCSharp/GetClassNameInCSharp/CarInfo.cs
csharp-basic-topics/GetClassNameInCSharp/GetClassNameInCSharp/GetClassNameInCSharp.csproj
csharp-basic-topics/GetClassNameInCSharp/GetClassNameInCSharp/Program.cs
csharp-basic-topics/GetClassNameInCSharp/Tests/CarInfoUnitTest.cs
csharp-basic-topics/GetClassNameInCSharp/Tests/CarUnitTest.cs
csharp-basic-topics/GetClassNameInCSharp/Tests/Tests.csproj
csharp-basic-topics/GetClassNameInCSharp/Tests/Usings.cs

CM-677
Code example for "How to get class name as a string in C#"

CM-677 : How to get class name as a string in C#

---

collections-lists/ArrayListInCSharp/ArrayListTests/ArrayListTests.cs

Code changes based on Senior Editor Review

CM-682: ArrayList in C# 

---

dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.Customers/Entities/Customer.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.Customers/IntroductionToScrutorInDotNet.Customers.csproj
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.Customers/Services/ICustomerService.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.Customers/Services/Implementations/CustomerService.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.sln
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Controllers/CustomersController.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Controllers/UsersController.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Entities/User.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet.csproj
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Program.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Properties/launchSettings.json
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Repositories/Decorators/RepositoryLoggerDecorator.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Repositories/IRepository.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Repositories/Implementations/UserRepository.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Services/IUserService.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/Services/Implementations/UserService.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/appsettings.Development.json
dependency-injection-tools/IntroductionToScrutorInDotNet/IntroductionToScrutorInDotNet/appsettings.json
dependency-injection-tools/IntroductionToScrutorInDotNet/Tests/CustomersControllerTests.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/Tests/Tests.csproj
dependency-injection-tools/IntroductionToScrutorInDotNet/Tests/UsersControllerTests.cs
dependency-injection-tools/IntroductionToScrutorInDotNet/Tests/Usings.cs

Adding code for CM-683: Introduction to Scrutor Library in .NET

CM-683: Introduction to Scrutor Library in .NET

---

dotnet-projects/MultipleFrameworkTarget/MultipleFrameworkTargetConsole.sln
dotnet-projects/MultipleFrameworkTarget/MultipleFrameworkTargetConsole/MultipleFrameworkTargetConsole.csproj
dotnet-projects/MultipleFrameworkTarget/MultipleFrameworkTargetConsole/Program.cs
dotnet-projects/MultipleFrameworkTarget/Tests/MultipleFrameworkTargetUnitTests.cs
dotnet-projects/MultipleFrameworkTarget/Tests/Tests.csproj
dotnet-projects/MultipleFrameworkTarget/Tests/Usings.cs

Added Example project for CM-763- How to Target Multiple Frameworks in a Single .NET Project

CM-763: How to Target Multiple Frameworks in a Single .NET Project

---

dotnet-client-libraries/ITextHeadersFooters/.gitignore
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters.sln
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/BigDocument.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/ConsoleManager/FakeConsole.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/ConsoleManager/IConsole.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/ConsoleManager/IConsoleLineCounter.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/ConsoleManager/RealConsole.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/ITextHeadersFooters.csproj
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/PdfCreatorManager/IPdfCreator.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/PdfCreatorManager/RealPdfCreator.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/PdfCreatorManager/UnitConverter.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/Program.cs
dotnet-client-libraries/ITextHeadersFooters/ITextHeadersFooters/UserMenu.cs
dotnet-client-libraries/ITextHeadersFooters/Tests/BigDocumentTest.cs
dotnet-client-libraries/ITextHeadersFooters/Tests/PdfRunnerTest.cs
dotnet-client-libraries/ITextHeadersFooters/Tests/Tests.csproj
dotnet-client-libraries/ITextHeadersFooters/Tests/UserMenuTest.cs
dotnet-client-libraries/ITextHeadersFooters/Tests/Usings.cs

Initial Project for CM-721: Adding Header and Footer to a PDF using IText

CM-721: Initial project

---

strings-csharp/StringFormattableString/StringFormattableString.sln
strings-csharp/StringFormattableString/StringFormattableString/FormattableStringsMethods.cs
strings-csharp/StringFormattableString/StringFormattableString/Program.cs
strings-csharp/StringFormattableString/StringFormattableString/StringFormattableString.csproj
strings-csharp/StringFormattableString/StringFormattableString/TemperatureFormat.cs
strings-csharp/StringFormattableString/StringFormattableStringTests/FormattableStringsUnitTests.cs
strings-csharp/StringFormattableString/StringFormattableStringTests/StringFormattableStringTests.csproj
strings-csharp/StringFormattableString/StringFormattableStringTests/Usings.cs

CM-714: Difference Between String, FormattableString, IFormattable in C#

---

dotnet-datetime/StopWatchCSharp/StopWatchCSharp.sln
dotnet-datetime/StopWatchCSharp/StopWatchCSharp/Program.cs
dotnet-datetime/StopWatchCSharp/StopWatchCSharp/StopWatchCSharp.csproj
dotnet-datetime/StopWatchCSharp/StopWatchCSharp/StopWatchMethods.cs
dotnet-datetime/StopWatchCSharp/StopWatchCSharpTests/GlobalUsings.cs
dotnet-datetime/StopWatchCSharp/StopWatchCSharpTests/StopWatchCSharpTests.csproj
dotnet-datetime/StopWatchCSharp/StopWatchCSharpTests/StopWatchUnitTests.cs

CM-801: How to Use StopWatch in C#

---

dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime.Tests/DateTimeOffsetVsDateTime.Tests.csproj
dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime.Tests/DateTimeOffsetVsDateTimeTest.cs
dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime.Tests/Usings.cs
dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime.sln
dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime.csproj
dotnet-datetime/DateTimeOffsetVsDateTime/DateTimeOffsetVsDateTime/Program.cs

CM361: DateTimeOffset vs DateTime

CM-361 DateTimeOffset vs DateTime

---

collections-arrays/ArrayPool/ArrayPool.Benchmark/ArrayPool.Benchmark.csproj
collections-arrays/ArrayPool/ArrayPool.Benchmark/Benchmark.cs
collections-arrays/ArrayPool/ArrayPool.Benchmark/Program.cs
collections-arrays/ArrayPool/ArrayPool.Tests/ArrayPool.Tests.csproj
collections-arrays/ArrayPool/ArrayPool.Tests/Tests.cs
collections-arrays/ArrayPool/ArrayPool.Tests/Usings.cs
collections-arrays/ArrayPool/ArrayPool.sln
collections-arrays/ArrayPool/ArrayPool/ArrayPool.csproj
collections-arrays/ArrayPool/ArrayPool/Methods/CreateCustomArrayPool.cs
collections-arrays/ArrayPool/ArrayPool/Methods/GetArrayPool.cs
collections-arrays/ArrayPool/ArrayPool/Program.cs

Array Pool first commit. Please for your review.

CM-798 Array Pool

---

collections-csharp/ConcurrentStackInCSharp/ConcurrentStackInCSharp.sln
collections-csharp/ConcurrentStackInCSharp/ConcurrentStackInCSharp/ConcurrentStackInCSharp.csproj
collections-csharp/ConcurrentStackInCSharp/ConcurrentStackInCSharp/DrawingTool.cs
collections-csharp/ConcurrentStackInCSharp/ConcurrentStackInCSharp/Program.cs
collections-csharp/ConcurrentStackInCSharp/Tests/DrawingToolTests.cs
collections-csharp/ConcurrentStackInCSharp/Tests/GlobalUsings.cs
collections-csharp/ConcurrentStackInCSharp/Tests/Tests.csproj

Added example and tests for ConcurrentStack article

CM-95 ConcurrentStack<T> in C#

---

dotnet-projects/SwitchingDotnetSdk/SwitchingDotnetSdk.sln
dotnet-projects/SwitchingDotnetSdk/SwitchingDotnetSdk/Program.cs
dotnet-projects/SwitchingDotnetSdk/SwitchingDotnetSdk/SwitchingDotnetSdk.csproj
dotnet-projects/SwitchingDotnetSdk/global.json

Added default project with global.json.

CM-184: Switching .NET SDK versions

---

csharp-basic-topics/EscapingBackSlashInCSharp/EscapingBackSlash.sln
csharp-basic-topics/EscapingBackSlashInCSharp/EscapingBackSlash/BackSlashMethods.cs
csharp-basic-topics/EscapingBackSlashInCSharp/EscapingBackSlash/EscapingBackSlash.csproj
csharp-basic-topics/EscapingBackSlashInCSharp/EscapingBackSlash/Program.cs
csharp-basic-topics/EscapingBackSlashInCSharp/Tests/Tests.cs
csharp-basic-topics/EscapingBackSlashInCSharp/Tests/Tests.csproj
csharp-basic-topics/EscapingBackSlashInCSharp/Tests/Usings.cs

JIRA Issue --> https://content.code-maze.com/browse/CM-916
Added different ways to escape the backslash character in C#

CM-916: How to Escape the Backslash Character in C#

---

collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp.sln
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp/CompareListsMethods.cs
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp/CompareStudentsExamples.cs
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp.csproj
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp/Program.cs
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharp/Student.cs
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharpTests/GlobalUsings.cs
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharpTests/ListExistsInAnotherCSharpTests.csproj
collections-lists/ListExistsInAnotherCSharp/ListExistsInAnotherCSharpTests/ListExistsInAnotherUnitTests.cs

CM-943: How to Check if Items of a List Exist in Another List in C#

---

csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface.sln
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/Basic/MyClass.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/DisposePattern/MyChildClass.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/DisposePattern/MyParentClass.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface.csproj
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/IManagedResource.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/ManagedResource.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/HowToImplementIDisposableInterface/Program.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/Tests/Basic/MyClassUnitTest.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/Tests/DisposePattern/MyChildClassUnitTest.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/Tests/DisposePattern/MyParentClassUnitTest.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/Tests/GlobalUsings.cs
csharp-intermediate-topics/HowToImplementIDisposableInterface/Tests/Tests.csproj
csharp-intermediate-topics/README.md

I created a demo code to show how to implement the IDisposable interface by using the Dispose pattern.
Followed these sources:
https://stackoverflow.com/questions/18336856/implementing-idisposable-correctly
https://www.codeproject.com/Articles/15360/Implementing-IDisposable-and-the-Dispose-Pattern-P
As requested in the task, it didn't cover the following:
https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects.

CM-140: How to (Correctly) Implement IDisposable Interface

---

dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharp.sln
dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharp/FirstDayOfWeekMethods.cs
dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharp.csproj
dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharp/Program.cs
dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharpTests/GetFirstDayOfWeekDateInCSharpTests.csproj
dotnet-datetime/GetFirstDayOfWeekDateInCSharp/GetFirstDayOfWeekDateInCSharpTests/GetFirstDayOfWeekDateUnitTests.cs

CM-1004: Get the Date of the First Day In a Week Given the Week Number and a Year In C#

---

strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharp.sln
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharp.csproj
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharp/Program.cs
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharp/StringHelper.cs
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharpTests/ConvertingStringToCharArrayInCSharpTests.csproj
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharpTests/StringHelperTests.cs
strings-csharp/ConvertingStringToCharArrayInCSharp/ConvertingStringToCharArrayInCSharpTests/Usings.cs

Converting string to char array in csharp

CM-884: Converting String to Char Array in C#

---

numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger.sln
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/BenchmarkReverseLargeNumber.cs
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/BenchmarkReverseNumber.cs
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/Program.cs
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/ReverseLargeNumbers.cs
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/ReverseNumberAsInteger.csproj
numbers-csharp/ReverseNumberAsInteger/ReverseNumberAsInteger/ReverseNumbers.cs
numbers-csharp/ReverseNumberAsInteger/Tests/GlobalUsings.cs
numbers-csharp/ReverseNumberAsInteger/Tests/ReverseNumberAsIntegerUnitTest.cs
numbers-csharp/ReverseNumberAsInteger/Tests/Tests.csproj

Initial Commit for Article **CM-1001 : How to Reverse a Number as an Integer and Not as a String in C#**
Jira Link - [CM-1001](https://content.code-maze.com/browse/CM-1001)
To run the code: 
\CodeMazeGuides\numbers-csharp\ReverseNumberAsInteger\reversenumberasinteger> dotnet run

CM-1001 : How to Reverse a Number as an Integer and Not as a String in C#

---

strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAString.sln
strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAString/Program.cs
strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAString/RemoveLastCharOfAString.csproj
strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAString/TechniquesToRemoveLastChar.cs
strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAStringTests/RemoveLastCharOfAStringTests.csproj
strings-csharp/RemoveLastCharOfAString/RemoveLastCharOfAStringTests/RemoveLastCharOfAStringUnitTests.cs

CM-902: The Fastest Way to Remove the Last Character of a String

---

collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes.sln
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes.csproj
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes/GenericListOfAnonymousTypesExamples.cs
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes/GenericMethod.cs
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypes/Program.cs
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypesTests/GenericListOfAnonymousTypesTests.csproj
collections-lists/GenericListOfAnonymousTypes/GenericListOfAnonymousTypesTests/GenericListUnitTests.cs

CM-1067: Different Ways to Create a Generic List of Anonymous Types in C#

---

json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson.sln
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Controllers/EmployeeController.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson.csproj
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson.http
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Models/Employee.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Program.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Properties/launchSettings.json
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Services/EmployeeService.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/Services/Interfaces/IEmployeeService.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/appsettings.Development.json
json-csharp/HandlingCircularRefsWhenWorkingWithJson/HandlingCircularRefsWhenWorkingWithJson/appsettings.json
json-csharp/HandlingCircularRefsWhenWorkingWithJson/Tests/IntegrationTest.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/Tests/StartUps/TestStartupWithIgnoreCycles.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/Tests/StartUps/TestStartupWithPreserve.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/Tests/StartUps/TestStartupWithoutReferenceHandler.cs
json-csharp/HandlingCircularRefsWhenWorkingWithJson/Tests/Tests.csproj

…Wrote integrationt tests to verify the json behaviour for each different scenario.

CM-1055: How to Handle Circular Reference When Working With JSON in .NET

---

aspnetcore-features/HowToSetDefaultUserAgentOnHttpClient/HowToSetDefaultUserAgentOnHttpClient.sln
aspnetcore-features/HowToSetDefaultUserAgentOnHttpClient/HowToSetDefaultUserAgentOnHttpClient/HowToSetDefaultUserAgentOnHttpClient.csproj
aspnetcore-features/HowToSetDefaultUserAgentOnHttpClient/HowToSetDefaultUserAgentOnHttpClient/Program.cs
aspnetcore-features/HowToSetDefaultUserAgentOnHttpClient/Tests/ProgramUnitTests.cs
aspnetcore-features/HowToSetDefaultUserAgentOnHttpClient/Tests/Tests.csproj

Pull request to merge the code sample implemented for the article CM335 - How Do I Set a Default User Agent on an HttpClient?

CM-335:How Do I Set a Default User Agent on an HttpClient?

---

strings-csharp/CheckNumberInString/CheckNumberInString.sln
strings-csharp/CheckNumberInString/CheckNumberInString/BenchmarkProcess.cs
strings-csharp/CheckNumberInString/CheckNumberInString/CheckNumberInString.csproj
strings-csharp/CheckNumberInString/CheckNumberInString/ExtractNumber.cs
strings-csharp/CheckNumberInString/CheckNumberInString/Program.cs
strings-csharp/CheckNumberInString/CheckNumberInStringTests/CheckNumberInStringTests.csproj
strings-csharp/CheckNumberInString/CheckNumberInStringTests/ExtractNumberTests.cs
strings-csharp/CheckNumberInString/CheckNumberInStringTests/GlobalUsings.cs

Different ways to find and extract number from string 
-Find and extract a number from a string Using RegEx 
-Find and extract a number from a string Using LINQ and Char.IsDigit 
-Find and extract a number from a string Using StringBuilder and Char.IsDigit

CM-989 Fastest Way to Find and Get a Number From a String in C#

---

.gitignore
aspnetcore-features/HSTS/HSTSExample.sln
aspnetcore-features/HSTS/HSTSExample/Controllers/WeatherForecastController.cs
aspnetcore-features/HSTS/HSTSExample/HSTSExample.csproj
aspnetcore-features/HSTS/HSTSExample/Program.cs
aspnetcore-features/HSTS/HSTSExample/Properties/launchSettings.json
aspnetcore-features/HSTS/HSTSExample/WeatherForecast.cs
aspnetcore-features/HSTS/HSTSExample/appsettings.Development.json
aspnetcore-features/HSTS/HSTSExample/appsettings.json
aspnetcore-features/HSTS/Tests/GlobalUsings.cs
aspnetcore-features/HSTS/Tests/Tests.csproj
aspnetcore-features/HSTS/Tests/WeatherForecastControllerTests.cs

CM-709- How to Implement HSTS Header in ASP.NET Core

CM-709: How to Implement HSTS Header in ASP.NET Core

---

dotnet-logging/Exceptionless/ExceptionlessTestClient.sln
dotnet-logging/Exceptionless/ExceptionlessTestClient/Controllers/ValuesController.cs
dotnet-logging/Exceptionless/ExceptionlessTestClient/ExceptionlessClient.csproj
dotnet-logging/Exceptionless/ExceptionlessTestClient/ExceptionlessTestClient.sln
dotnet-logging/Exceptionless/ExceptionlessTestClient/Program.cs
dotnet-logging/Exceptionless/ExceptionlessTestClient/Properties/launchSettings.json
dotnet-logging/Exceptionless/ExceptionlessTestClient/appsettings.Development.json
dotnet-logging/Exceptionless/ExceptionlessTestClient/appsettings.json
dotnet-logging/Exceptionless/Tests/Tests/GlobalUsings.cs
dotnet-logging/Exceptionless/Tests/Tests/Tests.csproj
dotnet-logging/Exceptionless/Tests/Tests/ValuesControllerTest.cs

CM-1045- Real-Time .NET Error Reporting With Exceptionless

CM-1045- Real-Time .NET Error Reporting With Exceptionless

---

aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync.sln
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync.csproj
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync.http
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Controllers/StockPriceController.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Data/StockPricesDbContext.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Models/ApiToken.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Models/StockPrice.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Program.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Properties/launchSettings.json
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Repositories/IStockPriceRepository.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Repositories/StockPriceRepository.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Services/IStockPriceService.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/Services/StockPriceService.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/StockPricesBackgroundService.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/appsettings.Development.json
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/BackgroundServiceExecuteAsyncAndStartAsync/appsettings.json
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/Tests/IntegrationTests.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/Tests/StartUps/StockPricesStartUp.cs
aspnetcore-features/BackgroundServiceExecuteAsyncAndStartAsync/Tests/Tests.csproj

CM-961 Initial implementation of the BackgroundService to show how we can use ExecuteAsync() and StartAsync()

CM-961: Comparing ExecuteAsync() and StartAsync() Methods from the BackgroundService Class in .NET

---

csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp.sln
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp/Employee.cs
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp/EmployeeComparer.cs
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp/ExceptMethodExamples.cs
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp/Program.cs
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharp/UsingExceptInCSharp.csproj
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharpTests/UsingExceptInCSharpTests.csproj
csharp-linq/UsingExceptInCSharp/UsingExceptInCSharpTests/UsingExceptUnitTests.cs

CM-1119: Using the Except Method in LINQ

---

dotnet-projects/windows-service/CodeMazeWorkerService/CodeMazeWorkerService.csproj
dotnet-projects/windows-service/CodeMazeWorkerService/Program.cs
dotnet-projects/windows-service/CodeMazeWorkerService/Worker.cs
dotnet-projects/windows-service/Tests/CodeMazeWorkerServiceTests.cs
dotnet-projects/windows-service/Tests/Tests.csproj

Upgraded to .NET8

---

dotnet-testing/LoadTestingWithJmeter/LoadTestingWithJmeter.sln
dotnet-testing/LoadTestingWithJmeter/Tests/GlobalUsings.cs
dotnet-testing/LoadTestingWithJmeter/Tests/Tests.csproj
dotnet-testing/LoadTestingWithJmeter/Tests/UsersControllerTests.cs
dotnet-testing/LoadTestingWithJmeter/UserService/Controllers/UsersController.cs
dotnet-testing/LoadTestingWithJmeter/UserService/Models/User.cs
dotnet-testing/LoadTestingWithJmeter/UserService/Program.cs
dotnet-testing/LoadTestingWithJmeter/UserService/Properties/launchSettings.json
dotnet-testing/LoadTestingWithJmeter/UserService/Services/IUserService.cs
dotnet-testing/LoadTestingWithJmeter/UserService/Services/UserService.cs
dotnet-testing/LoadTestingWithJmeter/UserService/UserAPI.csproj
dotnet-testing/LoadTestingWithJmeter/UserService/UserAPI.sln
dotnet-testing/LoadTestingWithJmeter/UserService/appsettings.Development.json
dotnet-testing/LoadTestingWithJmeter/UserService/appsettings.json

CM-1175: Load Testing ASP.NET Core Web API with JMeter

CM-1175: Load Testing ASP.NET Core Web API with JMeter

---

dotnet-projects/linux-service/CodeMazeLinuxWorker/CodeMazeLinuxWorker.csproj
dotnet-projects/linux-service/CodeMazeLinuxWorker/Program.cs
dotnet-projects/linux-service/CodeMazeLinuxWorker/Worker.cs
dotnet-projects/linux-service/Tests/Tests.csproj

Upgrade to .NET 8

---

csharp-advanced-topics/PointersInC#/PointersInC#/Method/Methods.cs
csharp-advanced-topics/PointersInC#/PointersInC#/PointersInCSharp.csproj
csharp-advanced-topics/PointersInC#/PointersInC#/Program.cs
csharp-advanced-topics/PointersInC#/PointersInCSharp.Tests/PointersInCSharp.Tests.csproj
csharp-advanced-topics/PointersInC#/PointersInCSharp.Tests/UnitTests.cs
csharp-advanced-topics/PointersInC#/PointersInCSharp.sln

First commit. Please for your review.

CM-1147 Pointers in CSharp first commit.
